# -*- coding: utf-8 -*-
"""langmem_tools.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HueQ8NnPGZRtJPVTd1ru-x5aTmjVQ8N0
"""

from langmem import create_manage_memory_tool, create_search_memory_tool

def get_memory_tools():
    manage_tool = create_manage_memory_tool(name="save_memory")
    search_tool = create_search_memory_tool(name="search_memory")
    return [manage_tool, search_tool]