# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L6UoJIa574itIeYy5q3VrZaAw9Z9xgUS
"""

from agent.research_agent import create_agent

agent = create_agent()
result = agent.invoke("How does LangMem manage semantic memory?")
print(result)